#!/usr/bin/env python3
import sys
from mcdata.nbt import print_tree
from mcdata.region import RegionFile

import sys
from mcdata.nbt import load, print_tree

# BrokenPipeError is new in Python 3.3.
# Earlier versions raise IOError.
try:
    error_type = BrokenPipeError
except NameError:
    error_type = IOError

def main():
    for filename in sys.argv[1:]:
        print('# File: {}'.format(filename))

        if filename.endswith('.mca'):
            for index, chunk in enumerate(RegionFile(filename)):
                if chunk:
                    print('# Chunk: {} ({})'.format(index, filename))
                    print_tree(chunk)
        else:
            print_tree(load(filename))

try:
    main()
except (error_type, KeyboardInterrupt):
    pass
