#!/usr/bin/env python3
import sys
from mcdata.nbt import print_tree
from mcdata.region import RegionFile

import sys
from mcdata.nbt import load, print_tree

PY33 = (sys.version_info.major, sys.version_info.minor) >= (3, 3)

def main():
    for filename in sys.argv[1:]:
        print('# File: {}'.format(filename))

        if filename.endswith('.mca'):
            for index, chunk in enumerate(RegionFile(filename)):
                if chunk:
                    print('# Chunk: {} ({})'.format(index, filename))
                    print_tree(chunk)
        else:
            print_tree(load(filename))

try:
    # Python 3.3 raises BrokenPipeError.
    # Earlier versions don't.
    if PY33:
        try:
            main()
        except BrokenPipeError:
            pass
    else:
        main()
except KeyboardInterrupt:
    pass
