#!/usr/bin/env python3
import sys
from mcdata.nbt import load, print_tree
from mcdata.region import RegionFile


def main():
    for filename in sys.argv[1:]:
        print('# File: {}'.format(filename))

        if filename.endswith('.mca'):
            for index, chunk in enumerate(RegionFile(filename)):
                if chunk:
                    print('# Chunk: {} ({})'.format(index, filename))
                    print_tree(chunk)
        else:
            print_tree(load(filename))


try:
    main()
except (BrokenPipeError, KeyboardInterrupt):
    pass
